title: Webroot.com/safe | Enter webroot keycode - Webroot Installation
description: Visit the Webroot Secure website at webroot.com/secure or www.webroot.com/safe from your browser. Enter your email address, enter your Webroot Keycode: Download and activate your Webroot secure setup on your device by entering the Webroot key code at webroot.com/safe.
